{
    "swagger": "2.0",
    "info": {
        "title": "Melodys API",
        "version": "0.5.0"
    },
    "host": "127.0.0.1:8000",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "paths": {
        "/api/user/registration": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "\u0410\u0434\u0440\u0435\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "description": "\u041d\u0438\u043a\u043d\u0435\u0439\u043c",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "description": "\u041f\u0430\u0440\u043e\u043b\u044c",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "r_password",
                        "in": "query",
                        "description": "\u041f\u043e\u0432\u0442\u043e\u0440 \u043f\u0430\u0440\u043e\u043b\u044f",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "terms",
                        "in": "query",
                        "description": "\u0421\u043e\u0433\u043b\u0430\u0441\u0438\u0435 \u0441 \u043f\u0440\u0430\u0432\u0438\u043b\u0430\u043c\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u0430",
                        "required": true,
                        "type": "boolean"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC91c2VyXC9sb2dpbiIsImlhdCI6MTU1NTYzMzgxMiwiZXhwIjoxNTU1NjM3NDEyLCJuYmYiOjE1NTU2MzM4MTIsImp0aSI6Ink0VGtxWG05TE40YWRQYnciLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.isl9JCJ7vUuakqRHMWvwlYtpZfSvj7KVNvm4uTj_GcY",
                                "token_type": "bearer",
                                "expires_in": 3600
                            }
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "examples": {
                            "application/json": {
                                "errors": {
                                    "field": [
                                        "\u041f\u043e\u043b\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f."
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "\u0410\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "\u0410\u0434\u0440\u0435\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "description": "\u041f\u0430\u0440\u043e\u043b\u044c",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC91c2VyXC9sb2dpbiIsImlhdCI6MTU1NTYzMzgxMiwiZXhwIjoxNTU1NjM3NDEyLCJuYmYiOjE1NTU2MzM4MTIsImp0aSI6Ink0VGtxWG05TE40YWRQYnciLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.isl9JCJ7vUuakqRHMWvwlYtpZfSvj7KVNvm4uTj_GcY",
                                "token_type": "bearer",
                                "expires_in": 3600
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Validation error",
                        "examples": {
                            "application/json": {
                                "errors": {
                                    "field": [
                                        "\u041f\u043e\u043b\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f."
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "\u0420\u0430\u0437\u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "\u0422\u043e\u043a\u0435\u043d",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/api/user/password_recovery": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "\u0412\u043e\u0441\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u0430\u0440\u043e\u043b\u044f",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "\u0410\u0434\u0440\u0435\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Validation error"
                    }
                }
            }
        },
        "/api/user/password_reset": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "\u0421\u0431\u0440\u043e\u0441 \u043f\u0430\u0440\u043e\u043b\u044f",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "\u0422\u043e\u043a\u0435\u043d",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Validation error"
                    }
                }
            }
        },
        "/api/user/me/profile": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "\u041f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0444\u0438\u043b\u044f \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u043e\u0433\u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "\u0422\u043e\u043a\u0435\u043d",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "name": "babycry",
                                "about": null,
                                "image": null,
                                "instagram": null,
                                "website": null,
                                "twitter": null,
                                "link": "a6mglyeypdjrvaeua3youbxn5n9otlpizxh",
                                "user_id": 1
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0444\u0438\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "\u0422\u043e\u043a\u0435\u043d",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "_method",
                        "in": "formData",
                        "description": "\u041c\u0435\u0442\u043e\u0434 \u0437\u0430\u043f\u0440\u043e\u0441\u0430 put",
                        "required": true,
                        "type": "string",
                        "enum": [
                            "put"
                        ]
                    },
                    {
                        "name": "name",
                        "in": "formData",
                        "description": "\u041d\u0438\u043a\u043d\u0435\u0439\u043c",
                        "type": "string"
                    },
                    {
                        "name": "link",
                        "in": "formData",
                        "description": "\u0421\u0441\u044b\u043b\u043a\u0430",
                        "type": "string"
                    },
                    {
                        "name": "about",
                        "in": "formData",
                        "description": "\u041e \u0441\u0435\u0431\u0435",
                        "type": "string"
                    },
                    {
                        "name": "image",
                        "in": "formData",
                        "description": "\u0410\u0432\u0430\u0442\u0430\u0440",
                        "type": "file"
                    },
                    {
                        "name": "instagram",
                        "in": "formData",
                        "description": "Instagram",
                        "type": "string"
                    },
                    {
                        "name": "twitter",
                        "in": "formData",
                        "description": "Twitter",
                        "type": "string"
                    },
                    {
                        "name": "website",
                        "in": "formData",
                        "description": "\u0412\u0435\u0431-\u0441\u0430\u0439\u0442",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "name": "babycry",
                                "about": null,
                                "image": null,
                                "instagram": null,
                                "website": null,
                                "twitter": null,
                                "link": "a6mglyeypdjrvaeua3youbxn5n9otlpizxh",
                                "user_id": 1
                            }
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "examples": {
                            "application/json": {
                                "errors": {
                                    "field": [
                                        "\u041f\u043e\u043b\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f."
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/api/user/{user}/profile": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "\u041f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0444\u0438\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043f\u043e ID",
                "parameters": [
                    {
                        "name": "user",
                        "in": "path",
                        "description": "ID \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "name": "babycry",
                                "about": null,
                                "image": null,
                                "instagram": null,
                                "website": null,
                                "twitter": null,
                                "link": "a6mglyeypdjrvaeua3youbxn5n9otlpizxh",
                                "user_id": 1
                            }
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "Following": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "integer"
                },
                "follower_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "date-time"
                },
                "deleted_at": {
                    "type": "date-time"
                }
            }
        },
        "PasswordReset": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "created_at": {
                    "type": "date-time"
                },
                "updated_at": {
                    "type": "date-time"
                }
            }
        },
        "Playlist": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "file"
                },
                "user_id": {
                    "type": "integer"
                },
                "playlist_type_id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "date"
                },
                "created_at": {
                    "type": "date-time"
                },
                "updated_at": {
                    "type": "date-time"
                },
                "deleted_at": {
                    "type": "date-time"
                }
            }
        },
        "PlaylistType": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "Pro": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "date-time"
                }
            }
        },
        "Profile": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "about": {
                    "type": "string"
                },
                "image": {
                    "type": "file"
                },
                "instagram": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "date-time"
                },
                "deleted_at": {
                    "type": "date-time"
                }
            }
        },
        "Track": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "file"
                },
                "file": {
                    "type": "file"
                },
                "duration": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "playlist_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "date-time"
                },
                "updated_at": {
                    "type": "date-time"
                },
                "deleted_at": {
                    "type": "date-time"
                }
            }
        },
        "User": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "created_at": {
                    "type": "date-time"
                },
                "updated_at": {
                    "type": "date-time"
                },
                "deleted_at": {
                    "type": "date-time"
                }
            }
        }
    }
}